name: yine
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  sqflite: any
  path: any
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: '^2.0.0'
  email_validator: '^2.1.16'
  http: '^0.13.5'
  google_nav_bar: '^5.0.6'

flutter:

  uses-material-design: true
  assets:
    - images/
